import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main>
            <div className="max-w-screen py-6 sm:px-6 lg:px-8 h-screen">
              {/* <!-- Replace with your content --> */}
              {children}
              {/* <!-- /End replace --> */}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
